package Kuis;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SMK TELKOM
 */
public class Kuis extends javax.swing.JFrame {

    /**
     * Creates new form Latihan5
     */
    public Kuis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nama = new javax.swing.JTextField();
        kelas = new javax.swing.JTextField();
        absen = new javax.swing.JTextField();
        mapel = new javax.swing.JTextField();
        nilai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Penilaian Siswa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(177, 11, 119, 18);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(84, 47, 38, 16);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Kelas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(84, 85, 36, 16);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Absen");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(84, 123, 40, 16);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Mapel");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(84, 161, 39, 16);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("Nilai");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(84, 199, 30, 16);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(193, 234, 77, 25);
        getContentPane().add(nama);
        nama.setBounds(142, 47, 154, 27);
        getContentPane().add(kelas);
        kelas.setBounds(142, 85, 154, 27);
        getContentPane().add(absen);
        absen.setBounds(142, 123, 154, 27);
        getContentPane().add(mapel);
        mapel.setBounds(142, 161, 154, 27);
        getContentPane().add(nilai);
        nilai.setBounds(142, 199, 154, 24);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(94, 277, 270, 149);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = nama.getText();
        String klas = kelas.getText();
        String abcent = absen.getText();
        int value = Integer.parseInt(nilai.getText());
        String pelajaran = mapel.getText();
        
        if(value == 100){
            String Keterangan = "Lulus Sempurna";
            hasil.setText(" Nama Siswa : "+name+ "\n" +" Kelas : " +klas+ "\n"+ "Absen : " +abcent+ "\n" + "Mapel : "+pelajaran+"\n"+"Nilai : "
                    +value+"\n"+"Keterangan : "+Keterangan+"\n");
            
        }
        else if(value >= 90){
            String Keterangan = "Lulus";
            hasil.setText(" Nama Siswa : "+name+ "\n" +" Kelas : " +klas+ "\n"+ "Absen : " +abcent+ "\n" + "Mapel : "+pelajaran+"\n"+"Nilai : "
                    +value+"\n"+"Keterangan : "+Keterangan+"\n");
            
        }
          else if(value >= 75){
            String Keterangan = "Lulus KKM";
            hasil.setText(" Nama Siswa : "+name+ "\n" +" Kelas : " +klas+ "\n"+ "Absen" +abcent+ "\n" + "Mapel : "+pelajaran+"\n"+"Nilai : "
                    +value+"\n"+"Keterangan : "+Keterangan+"\n");
            
        }
          else if(value >= 65){
            String Keterangan = "Remidi";
            hasil.setText(" Nama Siswa : "+name+ "\n" +" Kelas : " +klas+ "\n"+ "Absen : " +abcent+ "\n" + "Mapel : "+pelajaran+"\n"+"Nilai : "
                    +value+"\n"+"Keterangan : "+Keterangan+"\n");
            
        }  else if(value <65 ){
            String Keterangan = "Tidak Lulus";
            hasil.setText(" Nama Siswa : "+name+ "\n" +" Kelas : " +klas+ "\n"+ "Absen : " +abcent+ "\n" + "Mapel : "+pelajaran+"\n"+"Nilai : "
                    +value+"\n"+"Keterangan : "+Keterangan+"\n");
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField absen;
    private javax.swing.JTextArea hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kelas;
    private javax.swing.JTextField mapel;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nilai;
    // End of variables declaration//GEN-END:variables
}
